//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.42000。
// 
#pragma warning disable 1591

namespace AIPWeb.SignatureService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SignatureSoap", Namespace="http://tempuri.org/")]
    public partial class Signature : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AccountVerificationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUpdatePasswordUrlOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMailOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Signature() {
            this.Url = global::AIPWeb.Properties.Settings.Default.AIPWeb_SignatureService_Signature;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AccountVerificationCompletedEventHandler AccountVerificationCompleted;
        
        /// <remarks/>
        public event GetUpdatePasswordUrlCompletedEventHandler GetUpdatePasswordUrlCompleted;
        
        /// <remarks/>
        public event GetMailCompletedEventHandler GetMailCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AccountVerification", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AccountVerification(string account, string password) {
            object[] results = this.Invoke("AccountVerification", new object[] {
                        account,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AccountVerificationAsync(string account, string password) {
            this.AccountVerificationAsync(account, password, null);
        }
        
        /// <remarks/>
        public void AccountVerificationAsync(string account, string password, object userState) {
            if ((this.AccountVerificationOperationCompleted == null)) {
                this.AccountVerificationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAccountVerificationOperationCompleted);
            }
            this.InvokeAsync("AccountVerification", new object[] {
                        account,
                        password}, this.AccountVerificationOperationCompleted, userState);
        }
        
        private void OnAccountVerificationOperationCompleted(object arg) {
            if ((this.AccountVerificationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AccountVerificationCompleted(this, new AccountVerificationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUpdatePasswordUrl", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUpdatePasswordUrl(string id, string redirectUrl) {
            object[] results = this.Invoke("GetUpdatePasswordUrl", new object[] {
                        id,
                        redirectUrl});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUpdatePasswordUrlAsync(string id, string redirectUrl) {
            this.GetUpdatePasswordUrlAsync(id, redirectUrl, null);
        }
        
        /// <remarks/>
        public void GetUpdatePasswordUrlAsync(string id, string redirectUrl, object userState) {
            if ((this.GetUpdatePasswordUrlOperationCompleted == null)) {
                this.GetUpdatePasswordUrlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUpdatePasswordUrlOperationCompleted);
            }
            this.InvokeAsync("GetUpdatePasswordUrl", new object[] {
                        id,
                        redirectUrl}, this.GetUpdatePasswordUrlOperationCompleted, userState);
        }
        
        private void OnGetUpdatePasswordUrlOperationCompleted(object arg) {
            if ((this.GetUpdatePasswordUrlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUpdatePasswordUrlCompleted(this, new GetUpdatePasswordUrlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetMail(string unitCode1, string unitCode2, string signRoles) {
            object[] results = this.Invoke("GetMail", new object[] {
                        unitCode1,
                        unitCode2,
                        signRoles});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMailAsync(string unitCode1, string unitCode2, string signRoles) {
            this.GetMailAsync(unitCode1, unitCode2, signRoles, null);
        }
        
        /// <remarks/>
        public void GetMailAsync(string unitCode1, string unitCode2, string signRoles, object userState) {
            if ((this.GetMailOperationCompleted == null)) {
                this.GetMailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMailOperationCompleted);
            }
            this.InvokeAsync("GetMail", new object[] {
                        unitCode1,
                        unitCode2,
                        signRoles}, this.GetMailOperationCompleted, userState);
        }
        
        private void OnGetMailOperationCompleted(object arg) {
            if ((this.GetMailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMailCompleted(this, new GetMailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void AccountVerificationCompletedEventHandler(object sender, AccountVerificationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AccountVerificationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AccountVerificationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetUpdatePasswordUrlCompletedEventHandler(object sender, GetUpdatePasswordUrlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUpdatePasswordUrlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUpdatePasswordUrlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetMailCompletedEventHandler(object sender, GetMailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591