//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIPWeb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurance
    {
        public int Id { get; set; }
        public string No { get; set; }
        public string AccidentDate { get; set; }
        public string AccidentTime { get; set; }
        public string AccidentTerminal { get; set; }
        public string AccidentPlace { get; set; }
        public string AccidentProcess { get; set; }
        public string Remark { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
    }
}
